x-base-node: &base-node
  build: .
  volumes:
      - $PWD:/home/thoth/app
services:
  node-1:
    <<: *base-node
    ports:
      - 49221:49221
  node-2:
    <<: *base-node
    ports:
      - 49222:49221
    