x-base-node: &base-node
  build: .
  volumes:
      - $PWD:/home/thoth/app
  networks:
    thoth-net:
      aliases:
        - thoth-node
services:
  node-1:
    <<: *base-node
    ports:
      - 49221:49221
      - 50051:50051
  node-2:
    <<: *base-node
    ports:
      - 49222:49221
      - 50052:50051


networks:
  thoth-net:
    driver: bridge