# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mathop.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'mathop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmathop.proto\x12\x06mathop\"\x1b\n\tMatrixRow\x12\x0e\n\x06values\x18\x01 \x03(\x01\")\n\x06Matrix\x12\x1f\n\x04rows\x18\x01 \x03(\x0b\x32\x11.mathop.MatrixRow\"\\\n\x16MatrixOperationRequest\x12 \n\x08matrix_a\x18\x01 \x01(\x0b\x32\x0e.mathop.Matrix\x12 \n\x08matrix_b\x18\x02 \x01(\x0b\x32\x0e.mathop.Matrix\"U\n\x14MatrixOperationReply\x12%\n\rresult_matrix\x18\x01 \x01(\x0b\x32\x0e.mathop.Matrix\x12\x16\n\x0estatus_message\x18\x02 \x01(\t2Y\n\x07MathOps\x12N\n\x0eMatrixMultiply\x12\x1e.mathop.MatrixOperationRequest\x1a\x1c.mathop.MatrixOperationReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mathop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATRIXROW']._serialized_start=24
  _globals['_MATRIXROW']._serialized_end=51
  _globals['_MATRIX']._serialized_start=53
  _globals['_MATRIX']._serialized_end=94
  _globals['_MATRIXOPERATIONREQUEST']._serialized_start=96
  _globals['_MATRIXOPERATIONREQUEST']._serialized_end=188
  _globals['_MATRIXOPERATIONREPLY']._serialized_start=190
  _globals['_MATRIXOPERATIONREPLY']._serialized_end=275
  _globals['_MATHOPS']._serialized_start=277
  _globals['_MATHOPS']._serialized_end=366
# @@protoc_insertion_point(module_scope)
